
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class Przelew extends javax.swing.JFrame {
    String[] rachu;
    String[] nar={""};
    String pesel;
    /**
     * Creates new form Przelew
     */
    public Przelew(String[] rachunki,String pes) throws ClassNotFoundException, SQLException {
        initComponents();
        rachu=new String[rachunki.length];
        rachu=rachunki;
        jPrzeZR.removeAllItems();
        
        pesel=pes;
        
        Polaczenie conn=new Polaczenie();
        ResultSet result = conn.stmt.executeQuery("select nrrachunku from rachunek");
        result.last();
        int count=result.getRow();
        nar=new String[count];
        for(int j=0;j<count;j++)
        {
            result.absolute(j+1);
            nar[j]=result.getObject("nrrachunku").toString();
        }
        for(int i=0;i<rachu.length;i++){
            result = conn.stmt.executeQuery("select nrrachunku from rachunek where idrachunku="+rachu[i]+"");
            result.last();
            jPrzeZR.addItem(result.getObject("nrrachunku").toString());
        }
        jPrzeNaR.removeAllItems();
        conn.con.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPrzeZR = new javax.swing.JComboBox<>();
        jPrzeKwo = new javax.swing.JTextField();
        jPrzeTyt = new javax.swing.JTextField();
        jPrzeNaR = new javax.swing.JComboBox<>();
        jPrzeDod = new javax.swing.JButton();
        jPrzeAnu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Na rachunek:");

        jLabel2.setText("Kwota:");

        jLabel3.setText("Z rachunku:");

        jLabel4.setText("Tytułem:");

        jPrzeZR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPrzeZR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrzeZRActionPerformed(evt);
            }
        });

        jPrzeNaR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPrzeDod.setText("Wykonaj");
        jPrzeDod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrzeDodActionPerformed(evt);
            }
        });

        jPrzeAnu.setText("Anuluj");
        jPrzeAnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrzeAnuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPrzeZR, 0, 240, Short.MAX_VALUE)
                    .addComponent(jPrzeNaR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPrzeTyt)
                    .addComponent(jPrzeKwo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jPrzeDod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jPrzeAnu)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPrzeZR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPrzeNaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPrzeKwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPrzeTyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPrzeDod)
                    .addComponent(jPrzeAnu))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPrzeZRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrzeZRActionPerformed
            jPrzeNaR.removeAllItems();
            if(jPrzeZR.getItemCount()!=0){
            for(int i=0;i<nar.length;i++){
               // System.out.println(jPrzeZR.getSelectedItem().toString()+" "+nar[i]);
             if(jPrzeZR.getSelectedItem().toString().equals(nar[i])==false)
                 jPrzeNaR.addItem(nar[i]);
            }
            }// TODO add your handling code here:
    }//GEN-LAST:event_jPrzeZRActionPerformed

    private void jPrzeAnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrzeAnuActionPerformed
        Klient k;
        try {
            k = new Klient(pesel);
            k.setVisible(true);
                this.dispose(); 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Przelew.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Przelew.class.getName()).log(Level.SEVERE, null, ex);
        }
                
                       // TODO add your handling code here:
    }//GEN-LAST:event_jPrzeAnuActionPerformed

    private void jPrzeDodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrzeDodActionPerformed
        Polaczenie conn;
        Klient k;
        try {
            conn = new Polaczenie();
            ResultSet result = conn.stmt.executeQuery("select idrachunku from rachunek where nrrachunku="+jPrzeZR.getSelectedItem().toString()+"");
            result.last();
            String a=result.getObject("idrachunku").toString();
            result = conn.stmt.executeQuery("select idrachunku from rachunek where nrrachunku="+jPrzeNaR.getSelectedItem().toString()+"");
            result.last();
            String b=result.getObject("idrachunku").toString();
            conn.Przelew(a, b, jPrzeKwo.getText(), jPrzeTyt.getText());        // TODO add your handling code here:
            k = new Klient(pesel);
            k.setVisible(true);
                this.dispose();
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Przelew.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Przelew.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPrzeDodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Przelew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Przelew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Przelew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Przelew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jPrzeAnu;
    private javax.swing.JButton jPrzeDod;
    private javax.swing.JTextField jPrzeKwo;
    private javax.swing.JComboBox<String> jPrzeNaR;
    private javax.swing.JTextField jPrzeTyt;
    private javax.swing.JComboBox<String> jPrzeZR;
    // End of variables declaration//GEN-END:variables
}
